
name: mat244e
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24
  - pandas=1.5
  - matplotlib=3.7
  - sphinx
  - scipy=1.10
  - ipywidgets
  - statsmodels
  - scikit-learn
  - seaborn
  - plotly
  - pip:
    - session-info
    - jupyter-book
    - ghp-import